Bootstrap: docker
From: ubuntu:latest

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%post
    apt-get update
    apt-get install -y cowsay wget
    mkdir /data
    wget -O /data/pkg_data.txt https://figshare.com/ndownloader/files/34645619

# This does not work with a remote build instead we use
# wget in the %post section. If building on your own 
# system this would be the preferred way to include 
# data in the container
#%files
#    pkg_data.txt /data

%runscript
    cowsay "Hello Example-Easy"
