Bootstrap: docker
From: ubuntu:latest

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%post
    apt-get update
    apt-get install -y cowsay
    mkdir /data
    wget -O /data/pkg_data.txt https://figshare.com/ndownloader/files/34645619

%setup 
    touch pkg_data.txt

#%files
#    pkg_data.txt /opt

%runscript
    cowsay "Hello Example-Easy"
